//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_0623_A.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int managerId { get; set; }
        public string title { get; set; }
        public string department { get; set; }
        public string officePhone { get; set; }
        public string cellPhone { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string picture { get; set; }
    }
}
